### CREATE WILDERS
POST http://localhost:3000/api/wilder/create HTTP/1.1
content-type: application/json

{
    "name":"Http Wisdeeqelder",
    "city": "Londres",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}
### READ WILDERS
GET http://localhost:3000/api/wilder/read HTTP/1.1
content-type: application/json

### DELETE WILDERS 
DELETE http://localhost:3000/api/wilder/62277b818007eb62e7ff67ae/delete HTTP/1.1
content-type: application/json

### UPDATE WILDERS 
POST http://localhost:3000/api/wilder/62277be17397d0f1cbbcbabe/update HTTP/1.1
content-type: application/json

{
    "name":"Http Wisdqeldsqdjjiikqsdeeer",
    "city": "Pardsqdedis",
     "skills": [
    {
      "title": "HTML",
      "votes": 10,
      "_id": "622715d29cbf5cddeca11250"
    },
    {
      "title": "Reeaeect",
      "votes": 5,
      "_id": "622715d29cbf5cddeca11251"
    }
  ]
}