### CREATE WILDERS
POST http://localhost:3000/api/wilders HTTP/1.1
content-type: application/json

{
    "name":"wxcqxcwezaeazczeaezaezaeazxwcxw",
    "city": "Londres",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}
### READ WILDERS
GET http://localhost:3000/api/wilders HTTP/1.1
content-type: application/json

### DELETE WILDERS 
DELETE http://localhost:3000/api/wilder/6228b1e3811431c26904eb60/ HTTP/1.1
content-type: application/json

### UPDATE WILDERS 
POST http://localhost:3000/api/wilder/6228b2b159d29d81b1e369e7/ HTTP/1.1
content-type: application/json

{
    "name":"Http Wisdqeldsqdjjiikqsdeeer",
    "city": "Pardsqdedis",
     "skills": [
    {
      "title": "HTML",
      "votes": 10,
      "_id": "622715d29cbf5cddeca11250"
    },
    {
      "title": "Reeaeect",
      "votes": 5,
      "_id": "622715d29cbf5cddeca11251"
    }
  ]
}